// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Tue Nov 14 21:59:58 2017

soc_system soc_system_inst
(
	.clk_clk(clk_clk_sig) ,	// input  clk_clk_sig
	.hps_0_f2h_boot_from_fpga_boot_from_fpga_ready(hps_0_f2h_boot_from_fpga_boot_from_fpga_ready_sig) ,	// input  hps_0_f2h_boot_from_fpga_boot_from_fpga_ready_sig
	.hps_0_f2h_boot_from_fpga_boot_from_fpga_on_failure(hps_0_f2h_boot_from_fpga_boot_from_fpga_on_failure_sig) ,	// input  hps_0_f2h_boot_from_fpga_boot_from_fpga_on_failure_sig
	.hps_0_f2h_cold_reset_req_reset_n(hps_0_f2h_cold_reset_req_reset_n_sig) ,	// input  hps_0_f2h_cold_reset_req_reset_n_sig
	.hps_0_f2h_debug_reset_req_reset_n(hps_0_f2h_debug_reset_req_reset_n_sig) ,	// input  hps_0_f2h_debug_reset_req_reset_n_sig
	.hps_0_f2h_warm_reset_req_reset_n(hps_0_f2h_warm_reset_req_reset_n_sig) ,	// input  hps_0_f2h_warm_reset_req_reset_n_sig
	.hps_ddr3_mem_a(hps_ddr3_mem_a_sig) ,	// output [14:0] hps_ddr3_mem_a_sig
	.hps_ddr3_mem_ba(hps_ddr3_mem_ba_sig) ,	// output [2:0] hps_ddr3_mem_ba_sig
	.hps_ddr3_mem_ck(hps_ddr3_mem_ck_sig) ,	// output  hps_ddr3_mem_ck_sig
	.hps_ddr3_mem_ck_n(hps_ddr3_mem_ck_n_sig) ,	// output  hps_ddr3_mem_ck_n_sig
	.hps_ddr3_mem_cke(hps_ddr3_mem_cke_sig) ,	// output  hps_ddr3_mem_cke_sig
	.hps_ddr3_mem_cs_n(hps_ddr3_mem_cs_n_sig) ,	// output  hps_ddr3_mem_cs_n_sig
	.hps_ddr3_mem_ras_n(hps_ddr3_mem_ras_n_sig) ,	// output  hps_ddr3_mem_ras_n_sig
	.hps_ddr3_mem_cas_n(hps_ddr3_mem_cas_n_sig) ,	// output  hps_ddr3_mem_cas_n_sig
	.hps_ddr3_mem_we_n(hps_ddr3_mem_we_n_sig) ,	// output  hps_ddr3_mem_we_n_sig
	.hps_ddr3_mem_reset_n(hps_ddr3_mem_reset_n_sig) ,	// output  hps_ddr3_mem_reset_n_sig
	.hps_ddr3_mem_dq(hps_ddr3_mem_dq_sig) ,	// inout [31:0] hps_ddr3_mem_dq_sig
	.hps_ddr3_mem_dqs(hps_ddr3_mem_dqs_sig) ,	// inout [3:0] hps_ddr3_mem_dqs_sig
	.hps_ddr3_mem_dqs_n(hps_ddr3_mem_dqs_n_sig) ,	// inout [3:0] hps_ddr3_mem_dqs_n_sig
	.hps_ddr3_mem_odt(hps_ddr3_mem_odt_sig) ,	// output  hps_ddr3_mem_odt_sig
	.hps_ddr3_mem_dm(hps_ddr3_mem_dm_sig) ,	// output [3:0] hps_ddr3_mem_dm_sig
	.hps_ddr3_oct_rzqin(hps_ddr3_oct_rzqin_sig) ,	// input  hps_ddr3_oct_rzqin_sig
	.hps_io_hps_io_emac1_inst_TX_CLK(hps_io_hps_io_emac1_inst_TX_CLK_sig) ,	// output  hps_io_hps_io_emac1_inst_TX_CLK_sig
	.hps_io_hps_io_emac1_inst_TXD0(hps_io_hps_io_emac1_inst_TXD0_sig) ,	// output  hps_io_hps_io_emac1_inst_TXD0_sig
	.hps_io_hps_io_emac1_inst_TXD1(hps_io_hps_io_emac1_inst_TXD1_sig) ,	// output  hps_io_hps_io_emac1_inst_TXD1_sig
	.hps_io_hps_io_emac1_inst_TXD2(hps_io_hps_io_emac1_inst_TXD2_sig) ,	// output  hps_io_hps_io_emac1_inst_TXD2_sig
	.hps_io_hps_io_emac1_inst_TXD3(hps_io_hps_io_emac1_inst_TXD3_sig) ,	// output  hps_io_hps_io_emac1_inst_TXD3_sig
	.hps_io_hps_io_emac1_inst_RXD0(hps_io_hps_io_emac1_inst_RXD0_sig) ,	// input  hps_io_hps_io_emac1_inst_RXD0_sig
	.hps_io_hps_io_emac1_inst_MDIO(hps_io_hps_io_emac1_inst_MDIO_sig) ,	// inout  hps_io_hps_io_emac1_inst_MDIO_sig
	.hps_io_hps_io_emac1_inst_MDC(hps_io_hps_io_emac1_inst_MDC_sig) ,	// output  hps_io_hps_io_emac1_inst_MDC_sig
	.hps_io_hps_io_emac1_inst_RX_CTL(hps_io_hps_io_emac1_inst_RX_CTL_sig) ,	// input  hps_io_hps_io_emac1_inst_RX_CTL_sig
	.hps_io_hps_io_emac1_inst_TX_CTL(hps_io_hps_io_emac1_inst_TX_CTL_sig) ,	// output  hps_io_hps_io_emac1_inst_TX_CTL_sig
	.hps_io_hps_io_emac1_inst_RX_CLK(hps_io_hps_io_emac1_inst_RX_CLK_sig) ,	// input  hps_io_hps_io_emac1_inst_RX_CLK_sig
	.hps_io_hps_io_emac1_inst_RXD1(hps_io_hps_io_emac1_inst_RXD1_sig) ,	// input  hps_io_hps_io_emac1_inst_RXD1_sig
	.hps_io_hps_io_emac1_inst_RXD2(hps_io_hps_io_emac1_inst_RXD2_sig) ,	// input  hps_io_hps_io_emac1_inst_RXD2_sig
	.hps_io_hps_io_emac1_inst_RXD3(hps_io_hps_io_emac1_inst_RXD3_sig) ,	// input  hps_io_hps_io_emac1_inst_RXD3_sig
	.hps_io_hps_io_qspi_inst_IO0(hps_io_hps_io_qspi_inst_IO0_sig) ,	// inout  hps_io_hps_io_qspi_inst_IO0_sig
	.hps_io_hps_io_qspi_inst_IO1(hps_io_hps_io_qspi_inst_IO1_sig) ,	// inout  hps_io_hps_io_qspi_inst_IO1_sig
	.hps_io_hps_io_qspi_inst_IO2(hps_io_hps_io_qspi_inst_IO2_sig) ,	// inout  hps_io_hps_io_qspi_inst_IO2_sig
	.hps_io_hps_io_qspi_inst_IO3(hps_io_hps_io_qspi_inst_IO3_sig) ,	// inout  hps_io_hps_io_qspi_inst_IO3_sig
	.hps_io_hps_io_qspi_inst_SS0(hps_io_hps_io_qspi_inst_SS0_sig) ,	// output  hps_io_hps_io_qspi_inst_SS0_sig
	.hps_io_hps_io_qspi_inst_CLK(hps_io_hps_io_qspi_inst_CLK_sig) ,	// output  hps_io_hps_io_qspi_inst_CLK_sig
	.hps_io_hps_io_sdio_inst_CMD(hps_io_hps_io_sdio_inst_CMD_sig) ,	// inout  hps_io_hps_io_sdio_inst_CMD_sig
	.hps_io_hps_io_sdio_inst_D0(hps_io_hps_io_sdio_inst_D0_sig) ,	// inout  hps_io_hps_io_sdio_inst_D0_sig
	.hps_io_hps_io_sdio_inst_D1(hps_io_hps_io_sdio_inst_D1_sig) ,	// inout  hps_io_hps_io_sdio_inst_D1_sig
	.hps_io_hps_io_sdio_inst_CLK(hps_io_hps_io_sdio_inst_CLK_sig) ,	// output  hps_io_hps_io_sdio_inst_CLK_sig
	.hps_io_hps_io_sdio_inst_D2(hps_io_hps_io_sdio_inst_D2_sig) ,	// inout  hps_io_hps_io_sdio_inst_D2_sig
	.hps_io_hps_io_sdio_inst_D3(hps_io_hps_io_sdio_inst_D3_sig) ,	// inout  hps_io_hps_io_sdio_inst_D3_sig
	.hps_io_hps_io_usb1_inst_D0(hps_io_hps_io_usb1_inst_D0_sig) ,	// inout  hps_io_hps_io_usb1_inst_D0_sig
	.hps_io_hps_io_usb1_inst_D1(hps_io_hps_io_usb1_inst_D1_sig) ,	// inout  hps_io_hps_io_usb1_inst_D1_sig
	.hps_io_hps_io_usb1_inst_D2(hps_io_hps_io_usb1_inst_D2_sig) ,	// inout  hps_io_hps_io_usb1_inst_D2_sig
	.hps_io_hps_io_usb1_inst_D3(hps_io_hps_io_usb1_inst_D3_sig) ,	// inout  hps_io_hps_io_usb1_inst_D3_sig
	.hps_io_hps_io_usb1_inst_D4(hps_io_hps_io_usb1_inst_D4_sig) ,	// inout  hps_io_hps_io_usb1_inst_D4_sig
	.hps_io_hps_io_usb1_inst_D5(hps_io_hps_io_usb1_inst_D5_sig) ,	// inout  hps_io_hps_io_usb1_inst_D5_sig
	.hps_io_hps_io_usb1_inst_D6(hps_io_hps_io_usb1_inst_D6_sig) ,	// inout  hps_io_hps_io_usb1_inst_D6_sig
	.hps_io_hps_io_usb1_inst_D7(hps_io_hps_io_usb1_inst_D7_sig) ,	// inout  hps_io_hps_io_usb1_inst_D7_sig
	.hps_io_hps_io_usb1_inst_CLK(hps_io_hps_io_usb1_inst_CLK_sig) ,	// input  hps_io_hps_io_usb1_inst_CLK_sig
	.hps_io_hps_io_usb1_inst_STP(hps_io_hps_io_usb1_inst_STP_sig) ,	// output  hps_io_hps_io_usb1_inst_STP_sig
	.hps_io_hps_io_usb1_inst_DIR(hps_io_hps_io_usb1_inst_DIR_sig) ,	// input  hps_io_hps_io_usb1_inst_DIR_sig
	.hps_io_hps_io_usb1_inst_NXT(hps_io_hps_io_usb1_inst_NXT_sig) ,	// input  hps_io_hps_io_usb1_inst_NXT_sig
	.hps_io_hps_io_spim0_inst_CLK(hps_io_hps_io_spim0_inst_CLK_sig) ,	// output  hps_io_hps_io_spim0_inst_CLK_sig
	.hps_io_hps_io_spim0_inst_MOSI(hps_io_hps_io_spim0_inst_MOSI_sig) ,	// output  hps_io_hps_io_spim0_inst_MOSI_sig
	.hps_io_hps_io_spim0_inst_MISO(hps_io_hps_io_spim0_inst_MISO_sig) ,	// input  hps_io_hps_io_spim0_inst_MISO_sig
	.hps_io_hps_io_spim0_inst_SS0(hps_io_hps_io_spim0_inst_SS0_sig) ,	// output  hps_io_hps_io_spim0_inst_SS0_sig
	.hps_io_hps_io_spim1_inst_CLK(hps_io_hps_io_spim1_inst_CLK_sig) ,	// output  hps_io_hps_io_spim1_inst_CLK_sig
	.hps_io_hps_io_spim1_inst_MOSI(hps_io_hps_io_spim1_inst_MOSI_sig) ,	// output  hps_io_hps_io_spim1_inst_MOSI_sig
	.hps_io_hps_io_spim1_inst_MISO(hps_io_hps_io_spim1_inst_MISO_sig) ,	// input  hps_io_hps_io_spim1_inst_MISO_sig
	.hps_io_hps_io_spim1_inst_SS0(hps_io_hps_io_spim1_inst_SS0_sig) ,	// output  hps_io_hps_io_spim1_inst_SS0_sig
	.hps_io_hps_io_uart0_inst_RX(hps_io_hps_io_uart0_inst_RX_sig) ,	// input  hps_io_hps_io_uart0_inst_RX_sig
	.hps_io_hps_io_uart0_inst_TX(hps_io_hps_io_uart0_inst_TX_sig) ,	// output  hps_io_hps_io_uart0_inst_TX_sig
	.hps_io_hps_io_i2c1_inst_SDA(hps_io_hps_io_i2c1_inst_SDA_sig) ,	// inout  hps_io_hps_io_i2c1_inst_SDA_sig
	.hps_io_hps_io_i2c1_inst_SCL(hps_io_hps_io_i2c1_inst_SCL_sig) ,	// inout  hps_io_hps_io_i2c1_inst_SCL_sig
	.hps_io_hps_io_gpio_inst_HLGPI0(hps_io_hps_io_gpio_inst_HLGPI0_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI0_sig
	.hps_io_hps_io_gpio_inst_HLGPI1(hps_io_hps_io_gpio_inst_HLGPI1_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI1_sig
	.hps_io_hps_io_gpio_inst_HLGPI2(hps_io_hps_io_gpio_inst_HLGPI2_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI2_sig
	.hps_io_hps_io_gpio_inst_HLGPI3(hps_io_hps_io_gpio_inst_HLGPI3_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI3_sig
	.hps_io_hps_io_gpio_inst_HLGPI4(hps_io_hps_io_gpio_inst_HLGPI4_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI4_sig
	.hps_io_hps_io_gpio_inst_HLGPI5(hps_io_hps_io_gpio_inst_HLGPI5_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI5_sig
	.hps_io_hps_io_gpio_inst_HLGPI6(hps_io_hps_io_gpio_inst_HLGPI6_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI6_sig
	.hps_io_hps_io_gpio_inst_HLGPI7(hps_io_hps_io_gpio_inst_HLGPI7_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI7_sig
	.hps_io_hps_io_gpio_inst_HLGPI8(hps_io_hps_io_gpio_inst_HLGPI8_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI8_sig
	.hps_io_hps_io_gpio_inst_HLGPI9(hps_io_hps_io_gpio_inst_HLGPI9_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI9_sig
	.hps_io_hps_io_gpio_inst_HLGPI10(hps_io_hps_io_gpio_inst_HLGPI10_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI10_sig
	.hps_io_hps_io_gpio_inst_HLGPI11(hps_io_hps_io_gpio_inst_HLGPI11_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI11_sig
	.hps_io_hps_io_gpio_inst_HLGPI12(hps_io_hps_io_gpio_inst_HLGPI12_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI12_sig
	.hps_io_hps_io_gpio_inst_HLGPI13(hps_io_hps_io_gpio_inst_HLGPI13_sig) ,	// input  hps_io_hps_io_gpio_inst_HLGPI13_sig
	.hps_io_hps_io_gpio_inst_GPIO00(hps_io_hps_io_gpio_inst_GPIO00_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO00_sig
	.hps_io_hps_io_gpio_inst_GPIO09(hps_io_hps_io_gpio_inst_GPIO09_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO09_sig
	.hps_io_hps_io_gpio_inst_GPIO35(hps_io_hps_io_gpio_inst_GPIO35_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO35_sig
	.hps_io_hps_io_gpio_inst_GPIO40(hps_io_hps_io_gpio_inst_GPIO40_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO40_sig
	.hps_io_hps_io_gpio_inst_GPIO48(hps_io_hps_io_gpio_inst_GPIO48_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO48_sig
	.hps_io_hps_io_gpio_inst_GPIO53(hps_io_hps_io_gpio_inst_GPIO53_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO53_sig
	.hps_io_hps_io_gpio_inst_GPIO54(hps_io_hps_io_gpio_inst_GPIO54_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO54_sig
	.hps_io_hps_io_gpio_inst_GPIO55(hps_io_hps_io_gpio_inst_GPIO55_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO55_sig
	.hps_io_hps_io_gpio_inst_GPIO56(hps_io_hps_io_gpio_inst_GPIO56_sig) ,	// inout  hps_io_hps_io_gpio_inst_GPIO56_sig
	.hps_io_hps_io_gpio_inst_GPIO61(hps_io_hps_io_gpio_inst_GPIO61_sig) 	// inout  hps_io_hps_io_gpio_inst_GPIO61_sig
);

